export const products = [
  {
    id: '1',
    name: 'Truck 1',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
  {
    id: '2',
    name: 'Truck 2',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
  {
    id: '3',
    name: 'Truck 3',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
  {
    id: '4',
    name: 'Truck 4',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
  {
    id: '5',
    name: 'Truck 5',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
];

export const featuredProducts = [
  {
    id: '1',
    name: 'Truck 1',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
  {
    id: '2',
    name: 'Truck 2',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
  {
    id: '3',
    name: 'Truck 3',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
  {
    id: '4',
    name: 'Truck 4',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
  {
    id: '5',
    name: 'Truck 5',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
  {
    id: '6',
    name: 'Truck 6',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
  {
    id: '7',
    name: 'Truck 7',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
  {
    id: '8',
    name: 'Truck 8',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
  {
    id: '9',
    name: 'Truck 9',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
  {
    id: '10',
    name: 'Truck 10',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
];
