export const products = [
  {
    id: '1',
    name: 'Truck 1',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
  {
    id: '2',
    name: 'Truck 2',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
  {
    id: '3',
    name: 'Truck 3',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
  {
    id: '4',
    name: 'Truck 4',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
  {
    id: '5',
    name: 'Truck 5',
    tags: ['Cargo', 'Classic'],
    price: 3450000,
    model: 'Suzuki',
    year: 2000,
    make: 'Fronte',
    condition: 'Used',
  },
];
